version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: trajet_mongodb
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: myapp
    networks:
      - trajet_network

  minio:
    image: minio/minio
    container_name: trajet_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - trajet_network

  server:
    build: ./server
    container_name: trajet_server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/trajet
      - JWT_SECRET=6ba21a62dd9f50fbb177fd1bf9881f1527133b5e122394547a30addf0d8e8822fc6d6ca5a7ceeaca5a2918d30445d0830dd4bd68e55ba9f74e097c678cecf6dd
      - JWT_REFRESH_SECRET=94e3641099e5bc70f14b95effefbdecf958ebe0a0c6b7c95d83277b78fc4ec7cf46ba812fe377b32964f561aaeee2099b8735a2065123e14d22ad2303fc4c2e6
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - mongodb
      - minio
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    networks:
      - trajet_network

  client:
    build: ./client
    container_name: trajet_client
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://host.docker.internal:5000/api
    depends_on:
      - server
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    networks:
      - trajet_network

volumes:
  mongo_data:
  minio_data:
  server_node_modules:
  client_node_modules:
networks:
  trajet_network:
    driver: bridge